[server]

identity = /var/lib/rsqlite/.reticulum/identities/rsqlite-server
database = /var/lib/rsqlite/rsqlite.db
allowed_identities = /etc/rsqlite/allowed_identities
[announce]

enabled = no
announce_at_start = yes

