# rSQLite client configuration
#
# One or more remote rSQLite servers can be configured.
# Each server is identified by its Reticulum Destination Hash.

[identity]
file = ~/.reticulum/identities/rsqlite

[server.local]
name = Local Test
destination_hash = f299df21d181dbf672e3242dffd36218

[server.lab]
name = Debian Lab
destination_hash = 54f0c860a04dffcb10d93bddacc1305e
